package pojos;
// Generated Mar 15, 2021 11:53:28 AM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * AddItem generated by hbm2java
 */
public class AddItem  implements java.io.Serializable {


     private Integer recieveNo;
     private String itemCode;
     private String itemName;
     private String supplier;
     private String quantity;
     private Date date;

    public AddItem() {
    }

	
    public AddItem(String itemCode, String itemName, String supplier, String quantity) {
        this.itemCode = itemCode;
        this.itemName = itemName;
        this.supplier = supplier;
        this.quantity = quantity;
    }
    public AddItem(String itemCode, String itemName, String supplier, String quantity, Date date) {
       this.itemCode = itemCode;
       this.itemName = itemName;
       this.supplier = supplier;
       this.quantity = quantity;
       this.date = date;
    }
   
    public Integer getRecieveNo() {
        return this.recieveNo;
    }
    
    public void setRecieveNo(Integer recieveNo) {
        this.recieveNo = recieveNo;
    }
    public String getItemCode() {
        return this.itemCode;
    }
    
    public void setItemCode(String itemCode) {
        this.itemCode = itemCode;
    }
    public String getItemName() {
        return this.itemName;
    }
    
    public void setItemName(String itemName) {
        this.itemName = itemName;
    }
    public String getSupplier() {
        return this.supplier;
    }
    
    public void setSupplier(String supplier) {
        this.supplier = supplier;
    }
    public String getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(String quantity) {
        this.quantity = quantity;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }




}


