package pojos;
// Generated Mar 15, 2021 11:53:28 AM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * IssueItem generated by hbm2java
 */
public class IssueItem  implements java.io.Serializable {


     private String itemCode;
     private String itemName;
     private String epfNumber;
     private Date issueBy;
     private String quantity;

    public IssueItem() {
    }

	
    public IssueItem(String itemCode, String itemName, String epfNumber, String quantity) {
        this.itemCode = itemCode;
        this.itemName = itemName;
        this.epfNumber = epfNumber;
        this.quantity = quantity;
    }
    public IssueItem(String itemCode, String itemName, String epfNumber, Date issueBy, String quantity) {
       this.itemCode = itemCode;
       this.itemName = itemName;
       this.epfNumber = epfNumber;
       this.issueBy = issueBy;
       this.quantity = quantity;
    }
   
    public String getItemCode() {
        return this.itemCode;
    }
    
    public void setItemCode(String itemCode) {
        this.itemCode = itemCode;
    }
    public String getItemName() {
        return this.itemName;
    }
    
    public void setItemName(String itemName) {
        this.itemName = itemName;
    }
    public String getEpfNumber() {
        return this.epfNumber;
    }
    
    public void setEpfNumber(String epfNumber) {
        this.epfNumber = epfNumber;
    }
    public Date getIssueBy() {
        return this.issueBy;
    }
    
    public void setIssueBy(Date issueBy) {
        this.issueBy = issueBy;
    }
    public String getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(String quantity) {
        this.quantity = quantity;
    }




}


