import java.awt.image.ImageObserver;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.hibernate.Query;
//import javax.persistence.Query;
import org.hibernate.Session;
import org.hibernate.Transaction;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author user
 */
public class Add_item extends javax.swing.JFrame {
    

    /**
     * Creates new form add_item
     */
    public Add_item() {
        initComponents();
        //show_User();
    }    

    /*public ArrayList<User> userlist()
    {
        ArrayList<User> userslist = new ArrayList<>();
        try {
            
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/items", "root", "root");

            Statement st = con.createStatement();
            String sql= "SELECT * FROM Add_item";
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {           
                String r = String.valueOf(rs.getInt("Recieve_no"));
                String d = rs.getString("Item_Code");
                String e = rs.getString("Item_Name");
                String f = rs.getString("Supplier");
                String g = String.valueOf(rs.getInt("quantity"));
                String h = rs.getString("Date");
            }                      
            
            User user;
            while (rs.next()) {               
                user = new User(rs.getInt("Recieve_no"), rs.getString("Item_Code"), rs.getString("Item_Name"), rs.getString("Supplier"), rs.getInt("quantity"),rs.getString("Date"));
                userslist.add(user);
                System.out.println(userslist);
            }
        } 
        catch (Exception e) {            
            e.printStackTrace();
        }
        return userslist;

    }
    
    public void show_User() {
         
    }
    
    /*public List<pojos.AddItem> 
        findAllItemsWithJpql() {             
            Session s1 = connection.Controller.getSessionFactory().openSession();
            String sql = "SELECT a FROM Add_item a"; //2 times query diye h maybe issue isliye h ky??maybe not
            Query q = s1.createQuery(sql);
    return q.list(); //searching..wait     
}
    public void show_User() {    
            System.out.print(this);
            Session s1 = connection.Controller.getSessionFactory().openSession();
            Transaction tr = s1.beginTransaction();  
            String jpQL = "SELECT a FROM Add_item a";
            Query q = s1.createQuery(jpQL);
            List <pojos.AddItem> list = findAllItemsWithJpql();//q.getResultlist(); try once
            list.stream().forEach((adi) -> {       
                System.out.println(adi.getItemName());// isse runtime pe print hoga na haa ok
                DefaultTableModel model = (DefaultTableModel)table_user.getModel();
                Object row[] = new Object[12];//run kru?? yes
                
                row[0] = adi.getRecieveNo();
                row[1] = adi.getItemCode();
                row[2] = adi.getSupplier();
                row[3] = adi.getQuantity();
                row[4] = adi.getDate();
                model.addRow(row);
           
        });
        
    }*/

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
   // @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton13 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        n_supplier = new javax.swing.JTextField();
        n_quantity = new javax.swing.JTextField();
        n_itname = new javax.swing.JTextField();
        n_itcode = new javax.swing.JTextField();
        add_new = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        Add = new javax.swing.JButton();
        ex_itcode = new javax.swing.JComboBox();
        ex_itname = new javax.swing.JComboBox();
        ex_qty = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        rec_no = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        Add1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setBackground(new java.awt.Color(0, 153, 153));
        jLabel1.setFont(new java.awt.Font("Vani", 3, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Stock Management System");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(460, 30, 700, 70);

        jButton13.setBackground(new java.awt.Color(0, 153, 153));
        jButton13.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        jButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/businessman-icon-ffffff-35.png"))); // NOI18N
        jButton13.setText("  Suppliers");

        jButton15.setBackground(new java.awt.Color(0, 153, 153));
        jButton15.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        jButton15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/plus1.png"))); // NOI18N
        jButton15.setText("  Add Item  ");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        jButton16.setBackground(new java.awt.Color(0, 153, 153));
        jButton16.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        jButton16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/restart-icon-ffffff-35.png"))); // NOI18N
        jButton16.setText("  Backup   ");

        jButton17.setBackground(new java.awt.Color(0, 153, 153));
        jButton17.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        jButton17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/bill-icon-ffffff-35.png"))); // NOI18N
        jButton17.setText("  Reports   ");

        jButton18.setBackground(new java.awt.Color(0, 153, 153));
        jButton18.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        jButton18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/box-icon-ffffff-35.png"))); // NOI18N
        jButton18.setText("  Stock        ");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });

        jButton19.setBackground(new java.awt.Color(0, 153, 153));
        jButton19.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        jButton19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/arrow.png"))); // NOI18N
        jButton19.setText(" Issue Item");
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });

        jButton14.setBackground(new java.awt.Color(0, 153, 153));
        jButton14.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        jButton14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/manager-icon-18-ffffff-35.png"))); // NOI18N
        jButton14.setText("  Employee");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton17, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton15, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                    .addComponent(jButton19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton19, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton18, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(30, 130, 280, 560);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Forte", 0, 36)); // NOI18N
        jLabel4.setText("Add New  item ");

        jLabel9.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jLabel9.setText("Item code");

        n_supplier.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        n_supplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n_supplierActionPerformed(evt);
            }
        });

        n_quantity.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        n_quantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n_quantityActionPerformed(evt);
            }
        });

        n_itname.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        n_itname.setMaximumSize(new java.awt.Dimension(214, 2147483647));
        n_itname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n_itnameActionPerformed(evt);
            }
        });

        n_itcode.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        n_itcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n_itcodeActionPerformed(evt);
            }
        });

        add_new.setBackground(new java.awt.Color(102, 0, 102));
        add_new.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        add_new.setForeground(new java.awt.Color(240, 240, 240));
        add_new.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/plus1.png"))); // NOI18N
        add_new.setText("ADD");
        add_new.setMaximumSize(new java.awt.Dimension(109, 39));
        add_new.setMinimumSize(new java.awt.Dimension(109, 39));
        add_new.setPreferredSize(new java.awt.Dimension(109, 39));
        add_new.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_newActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jLabel6.setText("Item name");

        jLabel7.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jLabel7.setText("Quantity");

        jLabel8.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jLabel8.setText("Supplier");

        jLabel14.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jLabel14.setText("Low Stock Level");

        jLabel5.setFont(new java.awt.Font("Forte", 0, 36)); // NOI18N
        jLabel5.setText("Update Existing item ");

        jButton1.setBackground(new java.awt.Color(255, 255, 0));
        jButton1.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/brush-icon-ffffff-35.png"))); // NOI18N
        jButton1.setText("CLEAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextField3.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        Add.setBackground(new java.awt.Color(255, 0, 204));
        Add.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        Add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/plus1.png"))); // NOI18N
        Add.setText("ADD");
        Add.setMaximumSize(new java.awt.Dimension(109, 39));
        Add.setMinimumSize(new java.awt.Dimension(109, 39));
        Add.setPreferredSize(new java.awt.Dimension(109, 39));
        Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddActionPerformed(evt);
            }
        });

        ex_itcode.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        ex_itcode.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Item Code", "IC111", "IC112", "IC113", "IC114", "IC115", "IC116" }));
        ex_itcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ex_itcodeActionPerformed(evt);
            }
        });

        ex_itname.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        ex_itname.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Item name", "Nescafe", "Bruh Gold", "Davidoff", "Oreo" }));
        ex_itname.setToolTipText("");
        ex_itname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ex_itnameActionPerformed(evt);
            }
        });

        ex_qty.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        ex_qty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ex_qtyActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jLabel15.setText("Item name");

        jLabel16.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jLabel16.setText("Receipt No.");

        rec_no.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        rec_no.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Receipt No.", "100", "101", "102", "103", "104", "105" }));
        rec_no.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rec_noActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jLabel12.setText("Quantity");

        jLabel10.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jLabel10.setText("Item code");

        Add1.setBackground(new java.awt.Color(0, 204, 0));
        Add1.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        Add1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/logout.png"))); // NOI18N
        Add1.setText("EXIT");
        Add1.setMaximumSize(new java.awt.Dimension(109, 39));
        Add1.setMinimumSize(new java.awt.Dimension(109, 39));
        Add1.setPreferredSize(new java.awt.Dimension(109, 39));
        Add1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(Add, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(84, 84, 84)
                                .addComponent(jLabel14)
                                .addGap(5, 5, 5))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addGap(22, 22, 22)
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addGap(19, 19, 19)
                                            .addComponent(jLabel15)))
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rec_no, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ex_itcode, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ex_qty, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ex_itname, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(232, 232, 232)))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(n_itname, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                            .addComponent(n_quantity, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(n_itcode, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(n_supplier, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField3, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(30, 30, 30))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(533, 533, 533)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 124, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Add1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(24, 24, 24)
                        .addComponent(add_new, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rec_no, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(n_itname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ex_itcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(n_itcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(73, 73, 73)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ex_qty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(n_quantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(35, 35, 35)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ex_itname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(n_supplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(Add, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Add1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(add_new, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(350, 140, 990, 540);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/w-letter-company-logo-3102E4E551-seeklogo.com.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(60, -10, 210, 140);

        jButton7.setBackground(new java.awt.Color(255, 153, 51));
        jButton7.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/logout.png"))); // NOI18N
        jButton7.setText("Logout");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7);
        jButton7.setBounds(1140, 90, 180, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void n_supplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n_supplierActionPerformed
        // TODO add your handling code here:
         String ns_supplier = n_supplier.getText(); 
    }//GEN-LAST:event_n_supplierActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton18ActionPerformed

    private void add_newActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_newActionPerformed
        // TODO add your handling code here:
        try {
            Session s = connection.Controller.getSessionFactory().openSession();
            Transaction tr = s.beginTransaction();         
            pojos.AddItem a1 = new pojos.AddItem(); 
            
            String ns_itname=n_itname.getText();        
            a1.setItemName(ns_itname);
            
            String ns_itcode=n_itcode.getText();
            a1.setItemCode(ns_itcode);
                      
            String ns_supplier =n_supplier.getText();
            a1.setSupplier(ns_supplier);
            
            String ns_quantity=n_quantity.getText();
            a1.setQuantity(ns_quantity); 
            
            s.save(a1);   
            tr.commit();
            
            System.out.println("Saved Successfully..");
            JOptionPane.showMessageDialog(null, "New Item Added Succesfully!!");
            s.close();
            tr = null;
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog (null, e);
        
        }
    }//GEN-LAST:event_add_newActionPerformed
             
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int YesOrNo = JOptionPane.showConfirmDialog(null, "Are you sure you want to Clear data?","Clear Data",JOptionPane.YES_NO_OPTION);
            if(YesOrNo == 0){
        n_itcode.setText("");
        n_itname.setText("");
        n_itname.setText("");
        n_supplier.setText("");
        n_quantity.setText("");
        jTextField3.setText("");
        jTextField3.setText("");
        ex_qty.setText("");
        ex_itcode.setSelectedIndex(0);
        ex_itname.setSelectedIndex(0);
        rec_no.setSelectedIndex(0);
        
        JOptionPane.showMessageDialog(null, "DATA CLEARED SUCCESSFULLY!!");
            }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void n_itcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n_itcodeActionPerformed
        // TODO add your handling code here:
        String ns_itcode=n_itcode.getText();
    }//GEN-LAST:event_n_itcodeActionPerformed

    private void n_itnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n_itnameActionPerformed
        // TODO add your handling code here:
        String ns_itname=n_itname.getText();
    }//GEN-LAST:event_n_itnameActionPerformed

    private void n_quantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n_quantityActionPerformed
        // TODO add your handling code here:
         String ns_quantity=n_quantity.getText();
         int new_quantity =Integer.parseInt(ns_quantity);
         
    }//GEN-LAST:event_n_quantityActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddActionPerformed
        // TODO add your handling code here:
            Session s1 = connection.Controller.getSessionFactory().openSession();
            Transaction tr = s1.beginTransaction();  
            //String ex_code=ex_itcode.getSelectedItem().toString();             
            //String ex_itname1 = ex_itname.getSelectedItem().toString();                             
            String recp_no = rec_no.getSelectedItem().toString();
            int new_recp =Integer.parseInt(recp_no);
            String ex_qnty =ex_qty.getText();
            //int new_quantity =Integer.parseInt(ex_qty.getText());
            //a1.setQuantity(ns_quantity);
           
            
            pojos.AddItem ite = (pojos.AddItem) s1.load(pojos.AddItem.class,new_recp);
            String v = ite.getQuantity();
            
            ite.setQuantity(ex_qnty);
            //ite.setQuantity(ns_quantity);
            System.out.println("ite updated"+ ite.getQuantity());
            System.out.println("Rec no." + ite.getRecieveNo());
            s1.update(ite);
           
            JOptionPane.showMessageDialog(null, "Previous Item Quantity Updated from " +v +" to "+ ite.getQuantity()+" Successfully!!");
            JOptionPane.showMessageDialog(null, "Stocks Updated Successfully ");
//Query q = s1.createQuery("UPDATE Add_item SET Quantity = 80 WHERE Item_Code = 'IC111'") ; //2 times query diye h maybe issue isliye h ky??maybe not           
            //q.executeUpdate();
            /*
            s1.save(a1);   
            tr.commit();
            System.out.println("Updated Successfully..");
            
            s1.close();
            tr = null;
            */
    }//GEN-LAST:event_AddActionPerformed

    private void ex_itcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ex_itcodeActionPerformed
        // TODO add your handling code here:
        String ex_code = ex_itcode.getSelectedItem().toString();
    }//GEN-LAST:event_ex_itcodeActionPerformed
/*public List <pojos.AddItem> 
        findAllItemsWithJpql() {             
            Session s1 = connection.Controller.getSessionFactory().openSession();
            String sql = "SELECT a FROM Add_item a"; //2 times query diye h maybe issue isliye h ky??maybe not
            Query q = s1.createQuery(sql);
    return q.list(); //searching..wait     
}*/
        


    private void ex_itnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ex_itnameActionPerformed
        // TODO add your handling code here:
        String ex_itname1 = ex_itname.getSelectedItem().toString();
    }//GEN-LAST:event_ex_itnameActionPerformed

    private void ex_qtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ex_qtyActionPerformed
        // TODO add your handling code here:
         String ex_qnty =ex_qty.getText();
          
    }//GEN-LAST:event_ex_qtyActionPerformed

    private void rec_noActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rec_noActionPerformed
        // TODO add your handling code here:
       String recp_no = rec_no.getSelectedItem().toString();
    }//GEN-LAST:event_rec_noActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        dispose();
        
        
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        // TODO add your handling code here:
        //this.setVisible(false);
        new Issue_items().setVisible(true);
    }//GEN-LAST:event_jButton19ActionPerformed

    private void Add1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add1ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_Add1ActionPerformed
  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Add_item().setVisible(true);  
            }
           
            
        });
 }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add;
    private javax.swing.JButton Add1;
    private javax.swing.JButton add_new;
    private javax.swing.JComboBox ex_itcode;
    private javax.swing.JComboBox ex_itname;
    private javax.swing.JTextField ex_qty;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField n_itcode;
    private javax.swing.JTextField n_itname;
    private javax.swing.JTextField n_quantity;
    private javax.swing.JTextField n_supplier;
    private javax.swing.JComboBox rec_no;
    // End of variables declaration//GEN-END:variables
}
